Airflow v2
cityofaustin/atd-airflow pull request #118
Opened 2023-07-11 22:33 UTC by Charlie-Henry

## Associated issues

## Associated repo

## Testing

**Steps to test:**

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Add note to 1PW secrets moved to API vault and check for duplicates

2023-07-11 22:39 UTC, Charlie-Henry commented on dags/ped_data_pub.py
> +        return env_vars
Copying John's pattern from here:
https://github.com/cityofaustin/atd-airflow/pull/116

2023-07-12 14:18 UTC, johnclary requested changes, later dismissed
@Charlie-Henry this is looking great. just a few minor changes, and I'm going to start a Slack thread wrt to Socrata entries in 1password.

When I tested the code, it did process a bunch of data. Is that ok? On that note, would you mind adding a bit more detail to this repo's [readme](https://github.com/cityofaustin/atd-trail-counter-data)? It wasn't quickly obvious from the docs what this script was going to do, if we need to worry about duplicating data, and where the public dataset can be found.

2023-07-12 14:18 UTC, johnclary commented on dags/ped_data_pub.py
> +    start = "{{ prev_start_date_success.strftime('%Y-%m-%d') if prev_start_date_success or '1970-01-01'}}"
this was erroring for me until i changed `or` to `else`:

```
[2023-07-12, 13:59:53 UTC] {abstractoperator.py:597} ERROR - Exception rendering Jinja template for task 'trail_counter_data_publish', field 'command'. Template: "python counter_data.py --start {{ prev_start_date_success.strftime('%Y-%m-%d') if prev_start_date_success or '1970-01-01'}}"
Traceback (most recent call last):
....
jinja2.exceptions.UndefinedError: 'None' has no attribute 'strftime'
```

2023-07-12 14:18 UTC, johnclary commented on dags/ped_data_pub.py
> +    dag_id="atd_trail_counters",
it'd be nice to have this DAG's file name be more similar to the DAG name. e.g. `atd_trail_counters.py`

2023-07-12 16:52 UTC, frankhereford approved these changes
I agree with John's suggestions, esp with the bugfix and the filename. I was able to get this running, and I don't have anything valuable to add beyond a couple of imports that can get removed. This is great Charlie, and thanks for cleaning up this branch so we didn't loose your work!!

🚢 🚢 🚢

2023-07-12 16:52 UTC, frankhereford commented on dags/ped_data_pub.py
> +import os
It looks like this isn't used, so I think it can go.

2023-07-12 16:52 UTC, frankhereford commented on dags/ped_data_pub.py
> +from onepasswordconnectsdk.client import Client, new_client
Same with these, I think these are unused.

2023-07-12 16:52 UTC, frankhereford commented on dags/ped_data_pub.py
> +from utils.onepassword import load_dict
It looks like you're importing this in a function's namespace below, so I think this can be removed.

2023-07-12 16:53 UTC, Charlie-Henry commented
@johnclary 
> it did process a bunch of data. Is that ok?

Yes, likely used yesterday's date in the `--start` param and pulled in that data. Each row is protected by an ID so no duplication issues should arise. Run this script to your heart's content!

2023-07-12 17:11 UTC, Charlie-Henry commented
Since the file was renamed so lots of deltas here's what I addressed with my commit:
- Dropped unnecessary imports thx @frankhereford 
- `else` instead of `or` in the start param
-  Made a trail counters 1pass entry where the only item is the Socrata resource ID and is now pointing to that instead

[Dataset is here](https://datahub.austintexas.gov/Transportation-and-Mobility/Trail-Counters-Daily-Totals/26tt-cp67) internal because [blocked](https://github.com/cityofaustin/atd-data-tech/issues/8642)

2023-07-17 19:23 UTC, merged