Restart-reconfig-and-remove-vscode-settings
cityofaustin/atd-airflow pull request #199
Opened 2024-01-10 17:31 UTC by frankhereford

## Associated issues

none

## Intent

### Restart policy

This PR is to start a discussion mainly around the idea of changing our restart policies for airflow images. The idea is to:

1) Maintain the restart behavior of restarting airflow on our production machine
1) Chagne the restart behavior of having our local stacks of airflow start up on system restart of our dev computers.

`restart: unless-stopped` means to restart unless someone uses `docker compose stop` on the compose stack, which we'll never do intentionally on our production machine. So, on data03, `unless-stopped` is effectively `always` for our restart policy.

However, it plays out a little differently on our local machines. When we're done working on the airflow local stack, we can do a `docker compose stop` to stop our local stack, and it will stay down. With the `restart: always` policy in effect, it is configured to restart when the docker service daemon restarts, which means airflow fires up automatically on boot, which is not ideal.

### VSCode configurations

I want to set some VSCode configurations that I don't think anyone else is going to be interested in, such as a per-repo color scheme to help me differenciate my various vscode windows. There's nothing in the configuration that isn't already left-over frank config stuff, so I don't think this is a deal at all.

## Associated repo

airflow

## Testing

Really, the main thing we're looking for here is a non-event. Start the local stack, stop the local stack, and reboot your computer. When it comes back up, do a `docker ps`. Did airflow stay stopped? 

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Add note to 1PW secrets moved to API vault and check for duplicates

2024-01-10 17:36 UTC, frankhereford commented on docker-compose.yaml
> +      o: "bind"
YAML linting

2024-01-19 18:47 UTC, johnclary approved these changes
I tested this by making sure the docker stack came back up after i force quit Docker. It did, which is what we wan to happen on prod.

👍 Thanks!

2024-01-19 21:47 UTC, mddilley requested changes
Thanks, Frank! I read through the changes and your description. It all makes sense to me! 🚢 🚀

_Edit: Sorry - no changes requested. Hit the wrong button_ 🙃

2024-01-19 21:47 UTC, mddilley approved these changes
It works great if you select the correct radio - ship ship ship! ✅

2024-01-19 22:02 UTC, chiaberry approved these changes

2024-01-22 13:05 UTC, merged