Ch update docker images
cityofaustin/atd-airflow pull request #232
Opened 2024-05-24 20:43 UTC by Charlie-Henry

## Associated issues

## Associated repo

## Testing

**Steps to test:**

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Add note to 1PW secrets moved to API vault and check for duplicates

2024-05-24 21:01 UTC, Charlie-Henry commented
This DAG's file name and DAG name start with `dts`. Is that cool? Trying to follow what the repo is named.

2024-05-28 13:16 UTC, chiaberry approved these changes

2024-05-28 13:17 UTC, frankhereford commented
> This DAG's file name and DAG name start with `dts`. Is that cool? Trying to follow what the repo is named.

I think it's fine. I also think dropping the DTS is fine, since it's DTS' airflow instance, and I think that implies ownership of the DAG pretty well.

2024-05-28 13:28 UTC, frankhereford requested changes
A couple of tiny things -- otherwise this looks great and I'll ✅ as soon as you re-request review. Thanks Charlie!

Local airflow execution:

```
[2024-05-28, 08:21:27 CDT] {docker.py:359} INFO - Starting docker container from image atddocker/dts-maximo-reporting:production
[2024-05-28, 08:21:27 CDT] {docker.py:429} INFO - 2024-05-28 13:21:27,914 INFO: Getting work orders with start: 05/21/2024, end: 05/28/2024
[2024-05-28, 08:21:33 CDT] {docker.py:429} INFO - 2024-05-28 13:21:33,604 INFO: 1451 work orders found
[2024-05-28, 08:21:37 CDT] {docker.py:429} INFO - 2024-05-28 13:21:37,771 INFO: {'Errors': 0, 'Rows Created': 118, 'Rows Updated': 1333, 'Rows Deleted': 0}
[2024-05-28, 08:21:37 CDT] {taskinstance.py:441} ▶ Post task execution logs
```

2024-05-28 13:28 UTC, frankhereford commented on dags/dts_maximo_reporting_workorders.py
> +REQURED_SECRETS = {
Spelling error here -- luckily it has not spread too far. Do you mind fixing it in this DAG and in `atd_knack_employees_tpw_fire.py` also?

```
$ grep -rl "REQURED_SECRETS" .
./dags/atd_knack_employees_tpw_hire.py
./dags/dts_maximo_reporting_workorders.py
```

2024-05-28 13:28 UTC, frankhereford commented on dags/dts_maximo_reporting_workorders.py
> +from pendulum import datetime, duration, now
`now` is not used, it can be removed from the import

2024-05-28 13:28 UTC, frankhereford commented on dags/dts_maximo_reporting_workorders.py
> +    description="Uploads the last 7 days of Maximo workorders to Socrata from the Maximo data warehouse.",
`work orders` is two words, I believe.

2024-05-28 21:17 UTC, frankhereford approved these changes
Thanks!

2024-05-29 17:21 UTC, merged